# データ検証ルール設定ファイル
# TASK-102: データ検証・クレンジング機能用設定

# 基本検証設定
validation:
  # 社員ID検証
  employee_id:
    # 正規表現パターン
    pattern: "^[A-Z]{3}\\d{3,4}$"  # EMP001 または EMP0001 形式
    required: true
    max_length: 10
    
  # 社員名検証
  employee_name:
    required: true
    max_length: 50
    min_length: 1
    # 使用可能文字パターン
    allowed_chars: "^[\\u4e00-\\u9faf\\u3040-\\u309f\\u30a0-\\u30ffA-Za-z\\s]+$"  # 日本語・英語・スペース
    
  # 部署名検証
  department:
    required: false
    valid_departments:
      - "開発部"
      - "営業部" 
      - "総務部"
      - "経理部"
      - "人事部"
      - "マーケティング部"
      - "システム部"
    # 部署名マッピング（表記ゆれ対応）
    department_mapping:
      "開発課": "開発部"
      "開発チーム": "開発部"
      "開発グループ": "開発部"
      "Development": "開発部"
      "営業課": "営業部"
      "営業チーム": "営業部"
      "Sales": "営業部"
      "総務課": "総務部"
      "人事課": "人事部"
      "経理課": "経理部"

# 日付検証設定
date_validation:
  work_date:
    # 過去何年まで許可するか
    past_years: 5
    
    # 未来何日まで許可するか（0=未来日は全て警告）
    future_days: 0
    
    # 休日・祝日チェック
    check_holidays: false
    
    # 週末チェック
    check_weekends: false
    weekend_warning: true  # 週末勤務は警告レベル

# 時刻検証設定
time_validation:
  # 勤務時間制限
  work_hours:
    # 最大勤務時間（時間単位）
    max_daily_hours: 24.0
    
    # 最小勤務時間（時間単位）
    min_daily_hours: 0.5
    
    # 標準勤務時間（残業計算用）
    standard_hours: 8.0
    
    # 長時間労働警告しきい値（時間単位）
    overtime_warning_hours: 10.0
    
    # 深夜労働時間帯
    night_work_start: "22:00"
    night_work_end: "05:00"
  
  # 時刻フォーマット
  time_format:
    # 許可する入力フォーマット
    accepted_formats:
      - "HH:MM"
      - "HH:MM:SS" 
      - "H:MM"
      - "H時MM分"
    
    # 出力フォーマット
    output_format: "HH:MM"
    
    # 24時間制チェック
    check_24hour_format: true
    
  # 時刻論理チェック
  time_logic:
    # 出勤時刻 > 退勤時刻の場合の処理
    start_after_end_action: "warning"  # error, warning, ignore
    
    # 日跨ぎ勤務の最大時間（時間単位）
    max_crossover_hours: 16.0
    
    # 同時刻（0時間勤務）の処理
    zero_hours_action: "error"  # error, warning, ignore

# 休憩時間検証設定
break_time_validation:
  # 休憩時間制限（分単位）
  min_break_minutes: 0
  max_break_minutes: 480  # 8時間
  
  # デフォルト休憩時間（分単位）
  default_break_minutes: 60
  
  # 長時間勤務時の最低休憩時間
  mandatory_breaks:
    # 6時間超勤務時の最低休憩時間
    over_6_hours: 45
    # 8時間超勤務時の最低休憩時間  
    over_8_hours: 60
    # 10時間超勤務時の最低休憩時間
    over_10_hours: 90

# 勤務状態検証設定  
work_status_validation:
  # 有効な勤務状態リスト
  valid_statuses:
    - "出勤"
    - "欠勤"
    - "有給"
    - "特別休暇"
    - "半休"
    - "遅刻"
    - "早退"
    - "在宅勤務"
    - "出張"
    
  # ステータス別の時刻入力要否
  time_required:
    "出勤": true
    "遅刻": true 
    "早退": true
    "在宅勤務": true
    "出張": false
    "有給": false
    "欠勤": false
    "特別休暇": false
    "半休": true

# データ品質チェック設定
data_quality:
  # 品質スコア計算重み
  quality_weights:
    required_fields: 0.4      # 必須フィールド充足率
    valid_formats: 0.3        # フォーマット正確性
    logical_consistency: 0.2  # 論理整合性
    data_completeness: 0.1    # データ完全性
    
  # 品質しきい値
  quality_thresholds:
    excellent: 0.95   # 優秀
    good: 0.85        # 良好  
    acceptable: 0.70  # 許容可能
    poor: 0.50        # 要改善
    # poor未満は要修正

# エラーレベル設定
error_levels:
  # 重大度別処理
  CRITICAL:
    stop_processing: true
    require_manual_review: true
    
  ERROR: 
    stop_processing: false
    require_correction: true
    
  WARNING:
    stop_processing: false
    require_attention: true
    
  INFO:
    stop_processing: false
    log_only: true

# パフォーマンス設定
performance:
  # 並列処理
  enable_parallel: true
  max_workers: 4
  
  # 大量データ処理
  batch_size: 1000
  
  # メモリ制限（MB）
  memory_limit: 512
  
  # 処理タイムアウト（秒）
  timeout_seconds: 300

# ログ設定
logging:
  # ログレベル
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  
  # 詳細ログ出力対象
  detailed_logging:
    validation_errors: true
    performance_metrics: true
    data_quality_scores: true
    
  # ログローテーション
  max_log_files: 10
  max_log_size_mb: 100